baseURL = "/"
languageCode = "zh-CN"
defaultContentLanguage = "zh"

title = "姜宁博客"
theme = "learn"
themesdir = "./themes"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= false


[params]
  editURL = "https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/"
  description = "姜宁博客-西工网协-西安工业大学网页制作协会"
  author = "Johnny"
  disableSearch = true
  showVisitedLinks = false
  disableBreadcrumb = true
  disableNextPrev = false
  disableLandingPageButton = false
  themeVariant = "mine"
  disableMermaid = true
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = "|"


title = "姜宁博客"
weight = 3
languageName = "简体中文"
landingPageURL = "http://www.jnblog.cn/"
landingPageName = "<i class='fas fa-home'></i> 首页"

[[menu.shortcuts]] 
name = "<i class='fab fa-github'></i> 我的github"
identifier = "ds"
url = "https://github.com/matcornic/hugo-theme-learn"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-camera'></i> 获奖展示"
url = "/showcase"
weight = 11

[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> 项目成果"
identifier = "hugodoc"
url = "https://gohugo.io/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-bullhorn'></i> 我的视频"
url = "/credits"
weight = 30